
    # Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hr_pb2 as hr__pb2


class HRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmployee = channel.unary_unary(
                '/hr.HRService/GetEmployee',
                request_serializer=hr__pb2.GetEmployeeRequest.SerializeToString,
                response_deserializer=hr__pb2.GetEmployeeResponse.FromString,
                )
        self.CreateEmployee = channel.unary_unary(
                '/hr.HRService/CreateEmployee',
                request_serializer=hr__pb2.CreateEmployeeRequest.SerializeToString,
                response_deserializer=hr__pb2.CreateEmployeeResponse.FromString,
                )
        self.UpdateEmployee = channel.unary_unary(
                '/hr.HRService/UpdateEmployee',
                request_serializer=hr__pb2.UpdateEmployeeRequest.SerializeToString,
                response_deserializer=hr__pb2.UpdateEmployeeResponse.FromString,
                )
        self.DeleteEmployee = channel.unary_unary(
                '/hr.HRService/DeleteEmployee',
                request_serializer=hr__pb2.DeleteEmployeeRequest.SerializeToString,
                response_deserializer=hr__pb2.DeleteEmployeeResponse.FromString,
                )


class HRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=hr__pb2.GetEmployeeRequest.FromString,
                    response_serializer=hr__pb2.GetEmployeeResponse.SerializeToString,
            ),
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=hr__pb2.CreateEmployeeRequest.FromString,
                    response_serializer=hr__pb2.CreateEmployeeResponse.SerializeToString,
            ),
            'UpdateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmployee,
                    request_deserializer=hr__pb2.UpdateEmployeeRequest.FromString,
                    response_serializer=hr__pb2.UpdateEmployeeResponse.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=hr__pb2.DeleteEmployeeRequest.FromString,
                    response_serializer=hr__pb2.DeleteEmployeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hr.HRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hr.HRService/GetEmployee',
            hr__pb2.GetEmployeeRequest.SerializeToString,
            hr__pb2.GetEmployeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hr.HRService/CreateEmployee',
            hr__pb2.CreateEmployeeRequest.SerializeToString,
            hr__pb2.CreateEmployeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hr.HRService/UpdateEmployee',
            hr__pb2.UpdateEmployeeRequest.SerializeToString,
            hr__pb2.UpdateEmployeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hr.HRService/DeleteEmployee',
            hr__pb2.DeleteEmployeeRequest.SerializeToString,
            hr__pb2.DeleteEmployeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
